module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary as MTWOTGREQS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary
  field
    waveObservableTransportGeometryRegimeEquilibriumSummary :
      MTWOTGREQS.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeFidelitySummary
    MTWOTGREQS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
