module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeAlignmentSummary as MTWOTGRALIGN
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary
  field
    waveObservableTransportGeometryRegimeAlignmentSummary :
      MTWOTGRALIGN.MoonshineTwinedWaveObservableTransportGeometryRegimeAlignmentSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeIntegrationSummary
    MTWOTGRALIGN.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeAlignmentSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
