module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary as MTWOTGRCONTS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary
  field
    waveObservableTransportGeometryRegimeContinuitySummary :
      MTWOTGRCONTS.MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary
    MTWOTGRCONTS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
