module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryCoherenceSummary as MTWOTGCS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveRegimeSummary as MTWRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeSummary
  field
    waveObservableTransportGeometryCoherenceSummary :
      MTWOTGCS.MoonshineTwinedWaveObservableTransportGeometryCoherenceSummary
    waveRegimeSummary : MTWRS.MoonshineTwinedWaveRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeSummary
    MTWOTGCS.canonicalMoonshineTwinedWaveObservableTransportGeometryCoherenceSummary
    MTWRS.canonicalMoonshineTwinedWaveRegimeSummary
    2
