module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary as MTWOTGREQS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary
  field
    waveObservableTransportGeometryRegimeEquilibriumSummary :
      MTWOTGREQS.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary
    MTWOTGREQS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
