module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary as MTWOTGRBALS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary
  field
    waveObservableTransportGeometryRegimeBalanceSummary :
      MTWOTGRBALS.MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary
    MTWOTGRBALS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
