module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary as MTWOTGRSOS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary
  field
    waveObservableTransportGeometryRegimeSoundnessSummary :
      MTWOTGRSOS.MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary
    MTWOTGRSOS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
