module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary as MTWOTGRINVS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary
  field
    waveObservableTransportGeometryRegimeInvarianceSummary :
      MTWOTGRINVS.MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary
    MTWOTGRINVS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
