module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary as MTWOTGRINTS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary
  field
    waveObservableTransportGeometryRegimeIntegritySummary :
      MTWOTGRINTS.MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary
    MTWOTGRINTS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
