module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary as MTWOTGRHARS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary
  field
    waveObservableTransportGeometryRegimeHarmonySummary :
      MTWOTGRHARS.MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary
    MTWOTGRHARS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
