module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary as MTWOTGRROBS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary
  field
    waveObservableTransportGeometryRegimeRobustnessSummary :
      MTWOTGRROBS.MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary
    MTWOTGRROBS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
