module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCohesionSummary as MTWOTGRCOHS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
  field
    waveObservableTransportGeometryRegimeCohesionSummary :
      MTWOTGRCOHS.MoonshineTwinedWaveObservableTransportGeometryRegimeCohesionSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary
    MTWOTGRCOHS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCohesionSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
