module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary as MTWOTGRSYMS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary
  field
    waveObservableTransportGeometryRegimeSymmetrySummary :
      MTWOTGRSYMS.MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary
    MTWOTGRSYMS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
