module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary as MTWOTGRRESS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
  field
    waveObservableTransportGeometryRegimeResilienceSummary :
      MTWOTGRRESS.MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
    MTWOTGRRESS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
