module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary as MTWOTGRCS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveRegimeSummary as MTWRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary
  field
    waveObservableTransportGeometryRegimeCoherenceSummary :
      MTWOTGRCS.MoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary
    waveRegimeSummary : MTWRS.MoonshineTwinedWaveRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary
    MTWOTGRCS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary
    MTWRS.canonicalMoonshineTwinedWaveRegimeSummary
    2
