module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCompletenessSummary as MTWOTGRCMS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary as MTWOTGRCS

record MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary
  field
    waveObservableTransportGeometryRegimeCompletenessSummary :
      MTWOTGRCMS.MoonshineTwinedWaveObservableTransportGeometryRegimeCompletenessSummary
    waveObservableTransportGeometryRegimeCoherenceSummary :
      MTWOTGRCS.MoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary
    MTWOTGRCMS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCompletenessSummary
    MTWOTGRCS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary
    2
