module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary as MTWOTGRCONSS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary
  field
    waveObservableTransportGeometryRegimeConsistencySummary :
      MTWOTGRCONSS.MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary
    MTWOTGRCONSS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
