module DASHI.Physics.Closure.Consumers.WaveRegime where

-- Short-path compatibility layer for the current wave-regime consumer ladder.

open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.Consumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.CoherenceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.StabilityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.CompletenessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.SoundnessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ConsistencyConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.InvarianceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.RobustnessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ResilienceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.HarmonyConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.BalanceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.SymmetryConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ContinuityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.CompatibilityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ConcordanceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.CohesionConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.EquilibriumConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ConvergenceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.AlignmentConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.PrecisionConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ResolutionConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.CalibrationConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.NormalizationConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.RefinementConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.IntegrationConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.SynthesisConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.FusionConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.FidelityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.LegibilityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.TransparencyConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.ClarityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometry.Regime.IntegrityConsumer public
