module DASHI.Physics.Closure.Consumers.WaveRegime where

-- Short-path compatibility layer for the current wave-regime consumer ladder.

open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCoherenceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeStabilityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCompletenessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeSoundnessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConsistencyConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeInvarianceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeRobustnessConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeResilienceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeHarmonyConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeBalanceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeSymmetryConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeContinuityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCompatibilityConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConcordanceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCohesionConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConvergenceConsumer public
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeAlignmentConsumer public

