-- Auto-generated by erdfa-cli agda from /home/mdupont/2026/03-march/21/chboishabba/dashi_agda/da51_shards
module PerfHistory where

open import Agda.Builtin.Nat
open import Agda.Builtin.List
open import Agda.Builtin.String
open import Agda.Builtin.Bool

data CborVal : Set where
  cnat  : Nat → CborVal
  ctext : String → CborVal
  cpair : String → CborVal → CborVal
  clist : List CborVal → CborVal
  ctag  : Nat → CborVal → CborVal

shard-0 : CborVal
shard-0 = (ctag 55889 (clist
    ((cpair "file" (ctext "ActionMonotonicity.agda")) ∷ (cpair "sha256" (ctext "9b55de89582f2e0ef2e1426b07f6c02836aa332aa0d7ef047e00a361f683e886")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 34176685)) ∷ (cpair "instructions" (cnat 35438949)) ∷ (cpair "cache-misses" (cnat 194755)) ∷ (cpair "branch-misses" (cnat 226177)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "19ba03fba124ab650df8fa17a9df083debbd24eac9eb48a7d022c7c69fe2bf10")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 15015)) ∷ (cpair "denominators" (clist
            ((cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/3") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 15015) ∷ (cnat 235235) ∷ (cnat 2775773) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-1 : CborVal
shard-1 = (ctag 55889 (clist
    ((cpair "file" (ctext "AntiFascistSystem.agda")) ∷ (cpair "sha256" (ctext "04b34784271e339cfc8909c289921d57d93f974c78d8f9c3b8f1a4e91ffb7362")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 32007566)) ∷ (cpair "instructions" (cnat 47047885)) ∷ (cpair "cache-misses" (cnat 197821)) ∷ (cpair "branch-misses" (cnat 199100)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "3207a41668ccd1f8629b162412e183f3444ddb6bf2ab6f9a237f6e6106991113")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ (cnat 17) ∷ []))) ∷ (cpair "state" (cnat 24310)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 11) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/11") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 24310) ∷ (cnat 571285) ∷ (cnat 6741163) ∷ (cnat 43511143) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-2 : CborVal
shard-2 = (ctag 55889 (clist
    ((cpair "file" (ctext "Base369.agda")) ∷ (cpair "sha256" (ctext "d4f5ad1916787c76139985da63eeb24fd90449c7070cf284df6a29889f0487cd")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 28085810)) ∷ (cpair "instructions" (cnat 33206992)) ∷ (cpair "cache-misses" (cnat 126415)) ∷ (cpair "branch-misses" (cnat 190941)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "fbc6b9b79394497d3864bc121cb6dc709c875f4f2fa029962532f04821790c12")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 2730)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 2730) ∷ (cnat 64155) ∷ (cnat 1261715) ∷ (cnat 17916353) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-3 : CborVal
shard-3 = (ctag 55889 (clist
    ((cpair "file" (ctext "CRTPeriod.agda")) ∷ (cpair "sha256" (ctext "8440f88b4a7eabb912ed98a161ce5b435099768362d83b35ade32b7c492e1843")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 36157563)) ∷ (cpair "instructions" (cnat 51252696)) ∷ (cpair "cache-misses" (cnat 185875)) ∷ (cpair "branch-misses" (cnat 253438)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "40c864be3fe30948f90ec343de3c41fa0e6595eba8b32042300198a9d61654e5")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 132990)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 132990) ∷ (cnat 3125265) ∷ (cnat 61463545) ∷ (cnat 872782339) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-4 : CborVal
shard-4 = (ctag 55889 (clist
    ((cpair "file" (ctext "Contraction.agda")) ∷ (cpair "sha256" (ctext "2ac48ac31b501002642bacba234e3775d866511aa687ae163c10c64108ab930a")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 38424270)) ∷ (cpair "instructions" (cnat 53583336)) ∷ (cpair "cache-misses" (cnat 173104)) ∷ (cpair "branch-misses" (cnat 267430)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "3225d7901ced0831e2dde6bcbb6950f385a73428fa00b5c0cfe69c6143e48414")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 19) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 17670)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 17670) ∷ (cnat 415245) ∷ (cnat 8166485) ∷ (cnat 115964087) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-5 : CborVal
shard-5 = (ctag 55889 (clist
    ((cpair "file" (ctext "CounterexampleHarness.agda")) ∷ (cpair "sha256" (ctext "083b1d7c56252173477d17a754ecfd83d3a55af7de76b3f44f35488f657fd253")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 27729299)) ∷ (cpair "instructions" (cnat 33691238)) ∷ (cpair "cache-misses" (cnat 106099)) ∷ (cpair "branch-misses" (cnat 193088)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "3d6ce5bcd7cefa7ca15d7e926fcfca1678a7f0457f92e8c3308933f09eb218a6")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 7) ∷ (cnat 13) ∷ (cnat 23) ∷ []))) ∷ (cpair "state" (cnat 4186)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 7) ∷ (cnat 13) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/7") ∷ (ctext "71/13") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 4186) ∷ (cnat 98371) ∷ (cnat 829127) ∷ (cnat 4528309) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-6 : CborVal
shard-6 = (ctag 55889 (clist
    ((cpair "file" (ctext "DA51Tag.agda")) ∷ (cpair "sha256" (ctext "a192940a7538ae4c92b96d0942b25df4c949d64b7d17f97e69a467eada792357")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 39740515)) ∷ (cpair "instructions" (cnat 54293898)) ∷ (cpair "cache-misses" (cnat 227841)) ∷ (cpair "branch-misses" (cnat 277177)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "313d3ecf717f31d93eb4684e7a87d4875f6493edc8e13feead9f099a56999707")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "state" (cnat 30)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 30) ∷ (cnat 705) ∷ (cnat 13865) ∷ (cnat 196883) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-7 : CborVal
shard-7 = (ctag 55889 (clist
    ((cpair "file" (ctext "DA51Trace.agda")) ∷ (cpair "sha256" (ctext "3e019ae618ae2eeb2737c481e814df602e2d35eca87b810364ee7903db6be4d2")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 33055068)) ∷ (cpair "instructions" (cnat 34779718)) ∷ (cpair "cache-misses" (cnat 144286)) ∷ (cpair "branch-misses" (cnat 221276)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "4272ac5a48a16fbf8000826ad5be7d8ae1431cc55174c400396983fb371f1148")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 11) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 1254)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 11) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/11") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 1254) ∷ (cnat 29469) ∷ (cnat 579557) ∷ (cnat 3740777) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-8 : CborVal
shard-8 = (ctag 55889 (clist
    ((cpair "file" (ctext "DASHI_Tests.agda")) ∷ (cpair "sha256" (ctext "b8d0a74d9c40a3f164f45fa90a32b07db0de72076ea0aea8ad926653127754d7")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 43080283)) ∷ (cpair "instructions" (cnat 57194788)) ∷ (cpair "cache-misses" (cnat 248070)) ∷ (cpair "branch-misses" (cnat 244496)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "abc64efa9e97dba60bcdd9710cfa193eecfe92e4b8cd4e65ca79d72a84763aa4")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 19) ∷ (cnat 29) ∷ []))) ∷ (cpair "state" (cnat 115710)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 115710) ∷ (cnat 2719185) ∷ (cnat 53477305) ∷ (cnat 759377731) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-9 : CborVal
shard-9 = (ctag 55889 (clist
    ((cpair "file" (ctext "DaslImport.agda")) ∷ (cpair "sha256" (ctext "0f160f83ab3826b935c63536dbf20f4945c839d5029649c29cd0ea6e9bca6b59")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 27557559)) ∷ (cpair "instructions" (cnat 33533750)) ∷ (cpair "cache-misses" (cnat 130700)) ∷ (cpair "branch-misses" (cnat 193555)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "a83fddc5afa23b3ee40530d53ac8da16fe0d39de9192c94151e57d33586a5bab")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "state" (cnat 30)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 30) ∷ (cnat 705) ∷ (cnat 13865) ∷ (cnat 196883) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-10 : CborVal
shard-10 = (ctag 55889 (clist
    ((cpair "file" (ctext "Fascism_Tests.agda")) ∷ (cpair "sha256" (ctext "481aa099ee1c6de160efa83de3dcd1025ba091d559c4c375d0185f39ed87523f")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 46669044)) ∷ (cpair "instructions" (cnat 62040455)) ∷ (cpair "cache-misses" (cnat 218032)) ∷ (cpair "branch-misses" (cnat 264300)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "fe321529ffb6daf256c2a9fef3ec2e0ad3d0d26d51361f4b8c7196b146415242")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 930)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 930) ∷ (cnat 21855) ∷ (cnat 429815) ∷ (cnat 6103373) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-11 : CborVal
shard-11 = (ctag 55889 (clist
    ((cpair "file" (ctext "FascisticSystem.agda")) ∷ (cpair "sha256" (ctext "89e4324641d727081c5abd4a7fe9d5fdde92a3de3ed037c3da67be0fb1e4b0ff")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 33208240)) ∷ (cpair "instructions" (cnat 34868446)) ∷ (cpair "cache-misses" (cnat 157763)) ∷ (cpair "branch-misses" (cnat 214709)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "5dbf87dcb24252b38929a670b14617ec400cf309c3273b1f94f86a30e66ad7e6")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 1430)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 11) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/11") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 1430) ∷ (cnat 33605) ∷ (cnat 396539) ∷ (cnat 2559479) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-12 : CborVal
shard-12 = (ctag 55889 (clist
    ((cpair "file" (ctext "FixedPoint.agda")) ∷ (cpair "sha256" (ctext "170ae6b1afc141329feb2268128cd0d7efc6a13ab2d71a34d0a3aa83d8b69da4")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 59808320)) ∷ (cpair "instructions" (cnat 77809947)) ∷ (cpair "cache-misses" (cnat 402438)) ∷ (cpair "branch-misses" (cnat 309455)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "5fc4a44a2202b93c44b112e9539fb6e6554e9221ca7ae66988c0f03080ab8c7f")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 4290)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 4290) ∷ (cnat 100815) ∷ (cnat 1982695) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-13 : CborVal
shard-13 = (ctag 55889 (clist
    ((cpair "file" (ctext "HGSA_Fixpoints.agda")) ∷ (cpair "sha256" (ctext "c2063170df9bfa14b866ba97ce538f75b224db67c1f8034bafa157796ab399e3")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 27467033)) ∷ (cpair "instructions" (cnat 34334105)) ∷ (cpair "cache-misses" (cnat 139391)) ∷ (cpair "branch-misses" (cnat 188102)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "a7f161f9f900332ca4d06f6a046584888c3cedf144ef4a75175a9c718ca361a1")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 10010)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 10010) ∷ (cnat 235235) ∷ (cnat 2775773) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-14 : CborVal
shard-14 = (ctag 55889 (clist
    ((cpair "file" (ctext "JFixedPoint.agda")) ∷ (cpair "sha256" (ctext "1dc85d471f03ca520348e4b3f0bbc979b3b2bfe825d2ac7720e6a842f1b4004a")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 42527604)) ∷ (cpair "instructions" (cnat 65799009)) ∷ (cpair "cache-misses" (cnat 228228)) ∷ (cpair "branch-misses" (cnat 252973)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "6e0e005f2568adde4afc8290ee68d4622c93e682c32b2692fb63e9198269c485")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 7) ∷ (cnat 11) ∷ (cnat 13) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 114114)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 114114) ∷ (cnat 2681679) ∷ (cnat 52739687) ∷ (cnat 534931111) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-15 : CborVal
shard-15 = (ctag 55889 (clist
    ((cpair "file" (ctext "Layer0.agda")) ∷ (cpair "sha256" (ctext "0b1f062aee227599a8dcaf360dc4663a061200a6bcafd3b03a139cb24321ce81")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 37861033)) ∷ (cpair "instructions" (cnat 52881850)) ∷ (cpair "cache-misses" (cnat 109857)) ∷ (cpair "branch-misses" (cnat 256756)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "838853b792d2959ce4f76ac97c3dba948132d61e72bf678b12fa5a9e8372acf8")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 11) ∷ []))) ∷ (cpair "state" (cnat 2310)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 2310) ∷ (cnat 54285) ∷ (cnat 1067605) ∷ (cnat 15159991) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-16 : CborVal
shard-16 = (ctag 55889 (clist
    ((cpair "file" (ctext "Layer1.agda")) ∷ (cpair "sha256" (ctext "9522d67b2837be7d758b6f9465fc753c82739664ddf433a8d8769509e34fd618")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 31212908)) ∷ (cpair "instructions" (cnat 34732523)) ∷ (cpair "cache-misses" (cnat 144854)) ∷ (cpair "branch-misses" (cnat 208231)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "15443b602a42d5f17103bf976cebae42150cdc0d004b128a62927b625ffe410e")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 7) ∷ (cnat 23) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 9982)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 7) ∷ (cnat 23) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/7") ∷ (ctext "71/23") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 9982) ∷ (cnat 234577) ∷ (cnat 1977149) ∷ (cnat 6103373) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-17 : CborVal
shard-17 = (ctag 55889 (clist
    ((cpair "file" (ctext "Layer2.agda")) ∷ (cpair "sha256" (ctext "02807f7f2cbf7cf278f7079f525de713409326147303e80699e9d4fb11f44120")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 45778854)) ∷ (cpair "instructions" (cnat 56412865)) ∷ (cpair "cache-misses" (cnat 283639)) ∷ (cpair "branch-misses" (cnat 247169)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "e82e1bd5b39c62b80754af16cfea646123d59f164aab9815f1d46c92b0aadf1f")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 4290)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 4290) ∷ (cnat 100815) ∷ (cnat 1982695) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-18 : CborVal
shard-18 = (ctag 55889 (clist
    ((cpair "file" (ctext "Layer3.agda")) ∷ (cpair "sha256" (ctext "9c1c9e375d4e2f45085356b1ca8b47df3dd12e099d4056b0ce66ed0e388c8df2")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 44585055)) ∷ (cpair "instructions" (cnat 63563265)) ∷ (cpair "cache-misses" (cnat 220055)) ∷ (cpair "branch-misses" (cnat 358286)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "81ffa96c280762c9347eb23bc093dd0e2a5651f555c7000cfd75f3d6305556f9")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 6270)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 6270) ∷ (cnat 147345) ∷ (cnat 2897785) ∷ (cnat 41148547) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-19 : CborVal
shard-19 = (ctag 55889 (clist
    ((cpair "file" (ctext "LogicTlurey.agda")) ∷ (cpair "sha256" (ctext "ccee7396d94271b38daee3b9d61911a66355ec0052033618c27924792d64df05")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 36619759)) ∷ (cpair "instructions" (cnat 47505090)) ∷ (cpair "cache-misses" (cnat 154293)) ∷ (cpair "branch-misses" (cnat 250805)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "12a6b235fc81b63751620721f89140734958bfc88e7561423be49f4b6a0c4592")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ []))) ∷ (cpair "state" (cnat 330)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 330) ∷ (cnat 7755) ∷ (cnat 152515) ∷ (cnat 2165713) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-20 : CborVal
shard-20 = (ctag 55889 (clist
    ((cpair "file" (ctext "MaassRestoration.agda")) ∷ (cpair "sha256" (ctext "4240b9e65b973cda0ec650dfe7f922dc7e472f7c8d1e54e5a7d754134e521bbb")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 46128721)) ∷ (cpair "instructions" (cnat 62468277)) ∷ (cpair "cache-misses" (cnat 294258)) ∷ (cpair "branch-misses" (cnat 252415)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "66bec95648d7aae920137e68e2cbc05eed0a4bbc7909ea0dbd54376c954355f7")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 570)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 570) ∷ (cnat 13395) ∷ (cnat 263435) ∷ (cnat 3740777) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-21 : CborVal
shard-21 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterConformance.agda")) ∷ (cpair "sha256" (ctext "2c2f1da161cea1e3af0c1b356acbf8bcc1f67027cdb294f0da5177d55b7c001e")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 28353152)) ∷ (cpair "instructions" (cnat 33629960)) ∷ (cpair "cache-misses" (cnat 135673)) ∷ (cpair "branch-misses" (cnat 183132)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "c5a56d50151f04d7a9634d1b981c7e64a86d5e9bb0f69923ecbb1e529ac79291")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 2730)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 2730) ∷ (cnat 64155) ∷ (cnat 1261715) ∷ (cnat 17916353) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-22 : CborVal
shard-22 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterGroups.agda")) ∷ (cpair "sha256" (ctext "a4f5a5e6a0c070d119cf5f7c817260f75c02399da5fc41f14abdc9a76e3ea3c1")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 29218619)) ∷ (cpair "instructions" (cnat 34448659)) ∷ (cpair "cache-misses" (cnat 151255)) ∷ (cpair "branch-misses" (cnat 187442)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "8c2656ee5c8079776be3fa1032ddf9c74cdcdd18b0f242c7f3b29af01b2366ae")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 13) ∷ (cnat 17) ∷ []))) ∷ (cpair "state" (cnat 15470)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 15470) ∷ (cnat 363545) ∷ (cnat 4289831) ∷ (cnat 43511143) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-23 : CborVal
shard-23 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterOntos.agda")) ∷ (cpair "sha256" (ctext "7cb03b70693d9f202a57b41f847bb74f401208c27be7d7494237fadc38b48af5")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 21649820)) ∷ (cpair "instructions" (cnat 26651192)) ∷ (cpair "cache-misses" (cnat 118642)) ∷ (cpair "branch-misses" (cnat 141618)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "6c27da54740472adc48554fd1f436ad2120320b837addc512809273020386bad")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "state" (cnat 30)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 30) ∷ (cnat 705) ∷ (cnat 13865) ∷ (cnat 196883) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-24 : CborVal
shard-24 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterSpec.agda")) ∷ (cpair "sha256" (ctext "3730b28450831f914fd6d175d37712cc5b2b8e9aec1d7f5687c914ec8304db9f")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 28120351)) ∷ (cpair "instructions" (cnat 33714341)) ∷ (cpair "cache-misses" (cnat 131357)) ∷ (cpair "branch-misses" (cnat 185140)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "8735b0bd662f87f2b260d4e4195220cee9410b9450576f0f707cd445009f8cf7")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 19) ∷ (cnat 41) ∷ []))) ∷ (cpair "state" (cnat 54530)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 54530) ∷ (cnat 1281455) ∷ (cnat 15121169) ∷ (cnat 153371857) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-25 : CborVal
shard-25 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterState.agda")) ∷ (cpair "sha256" (ctext "65138e03abab170edbee24c82a916c19ef836c9317c35eaa717ae8f9ab0abc4f")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 28350211)) ∷ (cpair "instructions" (cnat 33734210)) ∷ (cpair "cache-misses" (cnat 126734)) ∷ (cpair "branch-misses" (cnat 185316)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "ac129d514c23ed3648f382184a44be2185e39a85e3456a07a55032120b753da8")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "state" (cnat 30)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 30) ∷ (cnat 705) ∷ (cnat 13865) ∷ (cnat 196883) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-26 : CborVal
shard-26 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterTraceCounts.agda")) ∷ (cpair "sha256" (ctext "48c6ce44605c8534c91e2019a16fa5e1929cfad2d87bd1e04c9a84cce0999a20")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 36020595)) ∷ (cpair "instructions" (cnat 46574509)) ∷ (cpair "cache-misses" (cnat 154694)) ∷ (cpair "branch-misses" (cnat 249444)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "41cf4d40206d9f4af0543d6246d069a195de439c3c339bf8494e7fa69eb64c11")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 13) ∷ (cnat 17) ∷ (cnat 41) ∷ []))) ∷ (cpair "state" (cnat 271830)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 271830) ∷ (cnat 6388005) ∷ (cnat 125630765) ∷ (cnat 1783956863) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-27 : CborVal
shard-27 = (ctag 55889 (clist
    ((cpair "file" (ctext "MonsterVectors.agda")) ∷ (cpair "sha256" (ctext "39bb74494af6d2faefb5a36c43b09938d5573ee704580c0cf92ddd0bb9669024")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 29409322)) ∷ (cpair "instructions" (cnat 33953540)) ∷ (cpair "cache-misses" (cnat 154381)) ∷ (cpair "branch-misses" (cnat 186715)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "cba94c6d4356322eebd2c53b89908f52106716854cd880772d6b470a4f460d59")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ []))) ∷ (cpair "state" (ctext "null")) ∷ (cpair "earns_moonshine" (ctext "false")) ∷ (cpair "reason" (ctext "only 2 SSP primes < 47")) ∷ []))) ∷ [])))

shard-28 : CborVal
shard-28 = (ctag 55889 (clist
    ((cpair "file" (ctext "Moonshine.agda")) ∷ (cpair "sha256" (ctext "1db6ae9cccef044a04025dba52a6518dc52d1ff24bdef2084c9c908a3728e4b8")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 37540519)) ∷ (cpair "instructions" (cnat 49799868)) ∷ (cpair "cache-misses" (cnat 174512)) ∷ (cpair "branch-misses" (cnat 254378)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "87182186dabbb26c80a9b78b237a6aa1e41dfc85f4c4210e879e346c0cc8fb7e")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 13) ∷ (cnat 17) ∷ []))) ∷ (cpair "state" (cnat 1326)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 13) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/13") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 1326) ∷ (cnat 31161) ∷ (cnat 612833) ∷ (cnat 3347011) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-29 : CborVal
shard-29 = (ctag 55889 (clist
    ((cpair "file" (ctext "MoonshineEarn.agda")) ∷ (cpair "sha256" (ctext "5fe46ad19640fa09d5b6bfb7d79e9a1d754b5be5e8da369b43701e2ae874174a")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 22260381)) ∷ (cpair "instructions" (cnat 26858344)) ∷ (cpair "cache-misses" (cnat 142874)) ∷ (cpair "branch-misses" (cnat 138937)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "a9b344d33af4e32e44afca40ebd6a2284813beab9aa31b5f58004cbd0625a950")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 11) ∷ (cnat 13) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 16302)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 11) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/11") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 16302) ∷ (cnat 383097) ∷ (cnat 7534241) ∷ (cnat 48630101) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-30 : CborVal
shard-30 = (ctag 55889 (clist
    ((cpair "file" (ctext "Overflow.agda")) ∷ (cpair "sha256" (ctext "7ca3a9c71d5951e261cccce8709305007e744592ba23c018b6d5e61131a1a74d")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 32416881)) ∷ (cpair "instructions" (cnat 33713113)) ∷ (cpair "cache-misses" (cnat 205155)) ∷ (cpair "branch-misses" (cnat 191910)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "1da05b2fab850903702911fd7ffeccde72e6221783d62675cc0d929c4206150d")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "state" (cnat 210)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 210) ∷ (cnat 4935) ∷ (cnat 97055) ∷ (cnat 1378181) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-31 : CborVal
shard-31 = (ctag 55889 (clist
    ((cpair "file" (ctext "PrimeRoles.agda")) ∷ (cpair "sha256" (ctext "813f9c3bb00e43a5cdf1c8a6934dba07a9cfb3ea9a885779a9af904e5a3d53b1")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 37663825)) ∷ (cpair "instructions" (cnat 47641004)) ∷ (cpair "cache-misses" (cnat 218285)) ∷ (cpair "branch-misses" (cnat 254532)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "14e219bf700e376bb94d0a6c11c8ed70b59a893e59d6c1dc7468090b522c09c1")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 17) ∷ (cnat 23) ∷ []))) ∷ (cpair "state" (cnat 11730)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 11730) ∷ (cnat 275655) ∷ (cnat 5421215) ∷ (cnat 76981253) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-32 : CborVal
shard-32 = (ctag 55889 (clist
    ((cpair "file" (ctext "ReflectAll.agda")) ∷ (cpair "sha256" (ctext "b955be78b94a46e68c46e729a68982a58f9d34947192723b22ae22204b8b2fa7")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 28422938)) ∷ (cpair "instructions" (cnat 31765115)) ∷ (cpair "cache-misses" (cnat 162479)) ∷ (cpair "branch-misses" (cnat 158914)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "002add7dfb03163963460ba245d9dc7befcb760753d7525b89a7590428f1c2ed")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "state" (cnat 70)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 70) ∷ (cnat 1645) ∷ (cnat 19411) ∷ (cnat 196883) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-33 : CborVal
shard-33 = (ctag 55889 (clist
    ((cpair "file" (ctext "SWAR_Equivalence.agda")) ∷ (cpair "sha256" (ctext "4770dfab0cdbcdffe2c5116f93b5786cc1d25a2f6eb5d0f0712f90f647aaf058")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 40860020)) ∷ (cpair "instructions" (cnat 86440413)) ∷ (cpair "cache-misses" (cnat 173716)) ∷ (cpair "branch-misses" (cnat 204869)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "99695e65117cbf5d8662e69bd5e476a225de7a192f218e74f1e0c45820810eca")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "state" (cnat 210)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 210) ∷ (cnat 4935) ∷ (cnat 97055) ∷ (cnat 1378181) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-34 : CborVal
shard-34 = (ctag 55889 (clist
    ((cpair "file" (ctext "SelfTrace.agda")) ∷ (cpair "sha256" (ctext "fc2e6da7af184743c3a5df39f15f2c4129bd758f105045666731e8ed2c68c1c9")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 27950781)) ∷ (cpair "instructions" (cnat 33516401)) ∷ (cpair "cache-misses" (cnat 121170)) ∷ (cpair "branch-misses" (cnat 188687)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "ad17d992d80a3b11a651e91801c2b822cfcdeb7bd99a5c0dad48129d1750e2bd")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 17) ∷ []))) ∷ (cpair "state" (cnat 3570)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 3570) ∷ (cnat 83895) ∷ (cnat 1649935) ∷ (cnat 23429077) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-35 : CborVal
shard-35 = (ctag 55889 (clist
    ((cpair "file" (ctext "SelfWitness.agda")) ∷ (cpair "sha256" (ctext "b2a62c677a6188d610bcb41ce2fa8661323eb2bb840a083b6c0519866ea40ed9")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 31239680)) ∷ (cpair "instructions" (cnat 40942867)) ∷ (cpair "cache-misses" (cnat 135965)) ∷ (cpair "branch-misses" (cnat 200002)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "bd4a8d0d5c1febb89485e6b49ea87e4cdf3e5aef54cc7b50221dd8f6fb545d49")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 11) ∷ (cnat 29) ∷ []))) ∷ (cpair "state" (cnat 22330)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 5) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/5") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 22330) ∷ (cnat 524755) ∷ (cnat 6192109) ∷ (cnat 62805677) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-36 : CborVal
shard-36 = (ctag 55889 (clist
    ((cpair "file" (ctext "TenfoldBridges.agda")) ∷ (cpair "sha256" (ctext "4cd2ee34cba96b027baa126c9365b5ce3c6a9369b87e633e5a5037aa0d2c7d6b")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 45251338)) ∷ (cpair "instructions" (cnat 59056016)) ∷ (cpair "cache-misses" (cnat 198393)) ∷ (cpair "branch-misses" (cnat 356620)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "e2ca4b162efff705257162db6aadb2f5dc3ac2c04c7fcc455e901a7726bd402c")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 4290)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 4290) ∷ (cnat 100815) ∷ (cnat 1982695) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-37 : CborVal
shard-37 = (ctag 55889 (clist
    ((cpair "file" (ctext "ThreeAdic_Attractor.agda")) ∷ (cpair "sha256" (ctext "5b345b9f42be4d8936eb9dd788cd06f9fcbc3e4eec5b96ef97c646bc768d6ef0")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 20863519)) ∷ (cpair "instructions" (cnat 26667200)) ∷ (cpair "cache-misses" (cnat 99882)) ∷ (cpair "branch-misses" (cnat 138719)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "687dd9869ea9eeb69a626921efb3e1a8edc3b7ffc4d6b2db762dc456e73e45b7")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 7) ∷ (cnat 19) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 123690)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 123690) ∷ (cnat 2906715) ∷ (cnat 57165395) ∷ (cnat 811748609) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-38 : CborVal
shard-38 = (ctag 55889 (clist
    ((cpair "file" (ctext "UFTC_Lattice.agda")) ∷ (cpair "sha256" (ctext "04564f65bc45b15d3f7cf0b9f48718a8b3fa28d526498caff75168d55dc8fe0a")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 30730184)) ∷ (cpair "instructions" (cnat 34327743)) ∷ (cpair "cache-misses" (cnat 162823)) ∷ (cpair "branch-misses" (cnat 198152)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "108f9d035c45cb5cf5b876e2d1342dca45fa930bb347f599660ce5a27f650040")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 17) ∷ (cnat 31) ∷ []))) ∷ (cpair "state" (cnat 3162)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 17) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/17") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 3162) ∷ (cnat 74307) ∷ (cnat 1461371) ∷ (cnat 6103373) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-39 : CborVal
shard-39 = (ctag 55889 (clist
    ((cpair "file" (ctext "Ultrametric.agda")) ∷ (cpair "sha256" (ctext "ece54f5f6c33a7d60ed1d9613ff8867892e668fb9f6dc28abee2a59c34a44939")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 31267728)) ∷ (cpair "instructions" (cnat 41754226)) ∷ (cpair "cache-misses" (cnat 140017)) ∷ (cpair "branch-misses" (cnat 208065)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "8d5506973e75d8cc84ef7e9e574cd9bbda0b62cbb7302995d2e8b58240333ddc")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ (cnat 11) ∷ (cnat 13) ∷ []))) ∷ (cpair "state" (cnat 4290)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 5) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/5") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 4290) ∷ (cnat 100815) ∷ (cnat 1982695) ∷ (cnat 28154269) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shard-40 : CborVal
shard-40 = (ctag 55889 (clist
    ((cpair "file" (ctext "Z6_RegularInverse.agda")) ∷ (cpair "sha256" (ctext "59ee997e66ca22fe5437ca32b1a527cfd04c19178a30add42bd6dfe0bc0030dc")) ∷ (cpair "counters" (clist
        ((cpair "cycles" (cnat 31116893)) ∷ (cpair "instructions" (cnat 35033488)) ∷ (cpair "cache-misses" (cnat 130017)) ∷ (cpair "branch-misses" (cnat 206561)) ∷ []))) ∷ (cpair "trace_sha256" (ctext "0927e733ea94555c29d118ca881ffae5f71e1a5c416c6c01dda67b0552fa63af")) ∷ (cpair "fractran" (clist
        ((cpair "ssp_primes" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 7) ∷ (cnat 19) ∷ []))) ∷ (cpair "state" (cnat 798)) ∷ (cpair "denominators" (clist
            ((cnat 2) ∷ (cnat 3) ∷ (cnat 7) ∷ []))) ∷ (cpair "fractions" (clist
            ((ctext "47/2") ∷ (ctext "59/3") ∷ (ctext "71/7") ∷ []))) ∷ (cpair "trace" (clist
            ((cnat 798) ∷ (cnat 18753) ∷ (cnat 368809) ∷ (cnat 3740777) ∷ []))) ∷ (cpair "steps" (cnat 3)) ∷ (cpair "earns_moonshine" (ctext "true")) ∷ []))) ∷ [])))

shards : List CborVal
shards =
  shard-0
  ∷ shard-1
  ∷ shard-2
  ∷ shard-3
  ∷ shard-4
  ∷ shard-5
  ∷ shard-6
  ∷ shard-7
  ∷ shard-8
  ∷ shard-9
  ∷ shard-10
  ∷ shard-11
  ∷ shard-12
  ∷ shard-13
  ∷ shard-14
  ∷ shard-15
  ∷ shard-16
  ∷ shard-17
  ∷ shard-18
  ∷ shard-19
  ∷ shard-20
  ∷ shard-21
  ∷ shard-22
  ∷ shard-23
  ∷ shard-24
  ∷ shard-25
  ∷ shard-26
  ∷ shard-27
  ∷ shard-28
  ∷ shard-29
  ∷ shard-30
  ∷ shard-31
  ∷ shard-32
  ∷ shard-33
  ∷ shard-34
  ∷ shard-35
  ∷ shard-36
  ∷ shard-37
  ∷ shard-38
  ∷ shard-39
  ∷ shard-40
  ∷ []
