module DASHI.Physics.Moonshine.Reports.WaveRegime where

-- Short-path compatibility layer for the current wave-regime moonshine reports.

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCoherenceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeStabilitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCompletenessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSoundnessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConsistencySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeInvarianceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeRobustnessSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeResilienceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeHarmonySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeBalanceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeSymmetrySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeContinuitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCompatibilitySummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConcordanceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeCohesionSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeEquilibriumSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeConvergenceSummary public
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometryRegimeAlignmentSummary public

