module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeRobustnessConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeInvarianceConsumer as CWOTGRINVC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem as KLRWOTGRROB

record WaveObservableTransportGeometryRegimeRobustnessConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeRobustnessConsumer
  field
    transportGeometryRegimeInvarianceConsumer :
      CWOTGRINVC.WaveObservableTransportGeometryRegimeInvarianceConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeRobustness :
      KLRWOTGRROB.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem

canonicalWaveObservableTransportGeometryRegimeRobustnessConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRINVC.WaveObservableTransportGeometryRegimeInvarianceConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeRobustnessConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeRobustnessConsumer waveObsTransportGeometryRegimeInvariance =
  waveObservableTransportGeometryRegimeRobustnessConsumer
    waveObsTransportGeometryRegimeInvariance
    KLRWOTGRROB.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem
