module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeAlignmentConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer as CWOTGREQC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem as KLRWOTGRALIGN

record WaveObservableTransportGeometryRegimeAlignmentConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeAlignmentConsumer
  field
    transportGeometryRegimeEquilibriumConsumer :
      CWOTGREQC.WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeAlignment :
      KLRWOTGRALIGN.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem

canonicalWaveObservableTransportGeometryRegimeAlignmentConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGREQC.WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeAlignmentConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeAlignmentConsumer prev =
  waveObservableTransportGeometryRegimeAlignmentConsumer
    prev
    KLRWOTGRALIGN.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem
