module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeStabilityConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCoherenceConsumer as CWOTGRCC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem as KLRWOTGRS

record WaveObservableTransportGeometryRegimeStabilityConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeStabilityConsumer
  field
    transportGeometryRegimeCoherenceConsumer :
      CWOTGRCC.WaveObservableTransportGeometryRegimeCoherenceConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeStability :
      KLRWOTGRS.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem

canonicalWaveObservableTransportGeometryRegimeStabilityConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCC.WaveObservableTransportGeometryRegimeCoherenceConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeStabilityConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeStabilityConsumer waveObsTransportGeometryRegimeCoherence =
  waveObservableTransportGeometryRegimeStabilityConsumer
    waveObsTransportGeometryRegimeCoherence
    KLRWOTGRS.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
