module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeFidelityConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConvergenceConsumer as CWOTGRCONVC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem as KLRWOTGRFID

record WaveObservableTransportGeometryRegimeFidelityConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeFidelityConsumer
  field
    transportGeometryRegimeConvergenceConsumer :
      CWOTGRCONVC.WaveObservableTransportGeometryRegimeConvergenceConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeFidelity :
      KLRWOTGRFID.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem

canonicalWaveObservableTransportGeometryRegimeFidelityConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCONVC.WaveObservableTransportGeometryRegimeConvergenceConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeFidelityConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeFidelityConsumer
    waveObservableTransportGeometryRegimeConvergence =
  waveObservableTransportGeometryRegimeFidelityConsumer
    waveObservableTransportGeometryRegimeConvergence
    KLRWOTGRFID.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem
