module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCompatibilityConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeContinuityConsumer as CWOTGRCONTC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompatibilityTheorem as KLRWOTGRCOMP

record WaveObservableTransportGeometryRegimeCompatibilityConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeCompatibilityConsumer
  field
    transportGeometryRegimeContinuityConsumer :
      CWOTGRCONTC.WaveObservableTransportGeometryRegimeContinuityConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeCompatibility :
      KLRWOTGRCOMP.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompatibilityTheorem

canonicalWaveObservableTransportGeometryRegimeCompatibilityConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCONTC.WaveObservableTransportGeometryRegimeContinuityConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeCompatibilityConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeCompatibilityConsumer waveObsTransportGeometryRegimeContinuity =
  waveObservableTransportGeometryRegimeCompatibilityConsumer
    waveObsTransportGeometryRegimeContinuity
    KLRWOTGRCOMP.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompatibilityTheorem
