module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCoherenceConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConsumer as CWOTGRC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem as KLRWOTGRC

record WaveObservableTransportGeometryRegimeCoherenceConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeCoherenceConsumer
  field
    transportGeometryRegimeConsumer :
      CWOTGRC.WaveObservableTransportGeometryRegimeConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeCoherence :
      KLRWOTGRC.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem

canonicalWaveObservableTransportGeometryRegimeCoherenceConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRC.WaveObservableTransportGeometryRegimeConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeCoherenceConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeCoherenceConsumer waveObsTransportGeometryRegime =
  waveObservableTransportGeometryRegimeCoherenceConsumer
    waveObsTransportGeometryRegime
    KLRWOTGRC.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
