module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConsistencyConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeSoundnessConsumer as CWOTGRSOC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem as KLRWOTGRCONS

record WaveObservableTransportGeometryRegimeConsistencyConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeConsistencyConsumer
  field
    transportGeometryRegimeSoundnessConsumer :
      CWOTGRSOC.WaveObservableTransportGeometryRegimeSoundnessConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeConsistency :
      KLRWOTGRCONS.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem

canonicalWaveObservableTransportGeometryRegimeConsistencyConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRSOC.WaveObservableTransportGeometryRegimeSoundnessConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeConsistencyConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeConsistencyConsumer waveObsTransportGeometryRegimeSoundness =
  waveObservableTransportGeometryRegimeConsistencyConsumer
    waveObsTransportGeometryRegimeSoundness
    KLRWOTGRCONS.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem
