module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCohesionConsumer as CWOTGRCOHC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem as KLRWOTGREQ

record WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeEquilibriumConsumer
  field
    transportGeometryRegimeCohesionConsumer :
      CWOTGRCOHC.WaveObservableTransportGeometryRegimeCohesionConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeEquilibrium :
      KLRWOTGREQ.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem

canonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCOHC.WaveObservableTransportGeometryRegimeCohesionConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer waveObsTransportGeometryRegimeCohesion =
  waveObservableTransportGeometryRegimeEquilibriumConsumer
    waveObsTransportGeometryRegimeCohesion
    KLRWOTGREQ.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
