module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeCohesionConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConcordanceConsumer as CWOTGRCONCC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem as KLRWOTGRCOH

record WaveObservableTransportGeometryRegimeCohesionConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeCohesionConsumer
  field
    transportGeometryRegimeConcordanceConsumer :
      CWOTGRCONCC.WaveObservableTransportGeometryRegimeConcordanceConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeCohesion :
      KLRWOTGRCOH.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem

canonicalWaveObservableTransportGeometryRegimeCohesionConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCONCC.WaveObservableTransportGeometryRegimeConcordanceConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeCohesionConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeCohesionConsumer waveObsTransportGeometryRegimeConcordance =
  waveObservableTransportGeometryRegimeCohesionConsumer
    waveObsTransportGeometryRegimeConcordance
    KLRWOTGRCOH.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
