module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeIntegrationConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeAlignmentConsumer as CWOTGRALIGNC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrationTheorem as KLRWOTGRINTG

record WaveObservableTransportGeometryRegimeIntegrationConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeIntegrationConsumer
  field
    transportGeometryRegimeAlignmentConsumer :
      CWOTGRALIGNC.WaveObservableTransportGeometryRegimeAlignmentConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeIntegration :
      KLRWOTGRINTG.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrationTheorem

canonicalWaveObservableTransportGeometryRegimeIntegrationConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRALIGNC.WaveObservableTransportGeometryRegimeAlignmentConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeIntegrationConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeIntegrationConsumer prev =
  waveObservableTransportGeometryRegimeIntegrationConsumer
    prev
    KLRWOTGRINTG.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrationTheorem
