module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConvergenceConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeEquilibriumConsumer as CWOTGREQC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem as KLRWOTGRCONV

record WaveObservableTransportGeometryRegimeConvergenceConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeConvergenceConsumer
  field
    transportGeometryRegimeEquilibriumConsumer :
      CWOTGREQC.WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeConvergence :
      KLRWOTGRCONV.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem

canonicalWaveObservableTransportGeometryRegimeConvergenceConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGREQC.WaveObservableTransportGeometryRegimeEquilibriumConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeConvergenceConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeConvergenceConsumer
    waveObservableTransportGeometryRegimeEquilibrium =
  waveObservableTransportGeometryRegimeConvergenceConsumer
    waveObservableTransportGeometryRegimeEquilibrium
    KLRWOTGRCONV.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem
