module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeInvarianceConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeConsistencyConsumer as CWOTGRCONSC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem as KLRWOTGRINV

record WaveObservableTransportGeometryRegimeInvarianceConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeInvarianceConsumer
  field
    transportGeometryRegimeConsistencyConsumer :
      CWOTGRCONSC.WaveObservableTransportGeometryRegimeConsistencyConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeInvariance :
      KLRWOTGRINV.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem

canonicalWaveObservableTransportGeometryRegimeInvarianceConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRCONSC.WaveObservableTransportGeometryRegimeConsistencyConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeInvarianceConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeInvarianceConsumer waveObsTransportGeometryRegimeConsistency =
  waveObservableTransportGeometryRegimeInvarianceConsumer
    waveObsTransportGeometryRegimeConsistency
    KLRWOTGRINV.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
