module DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeIntegrityConsumer where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.MinimalCrediblePhysicsClosure as MCPC
open import DASHI.Physics.Closure.CanonicalWaveObservableTransportGeometryRegimeResilienceConsumer as CWOTGRRESC
open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem as KLRWOTGRINT

record WaveObservableTransportGeometryRegimeIntegrityConsumerFromMinimal
         (cl : MCPC.MinimalCrediblePhysicsClosure) : Setω where
  constructor waveObservableTransportGeometryRegimeIntegrityConsumer
  field
    transportGeometryRegimeResilienceConsumer :
      CWOTGRRESC.WaveObservableTransportGeometryRegimeResilienceConsumerFromMinimal cl
    recoveredWaveObservableTransportGeometryRegimeIntegrity :
      KLRWOTGRINT.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem

canonicalWaveObservableTransportGeometryRegimeIntegrityConsumer :
  {cl : MCPC.MinimalCrediblePhysicsClosure} →
  CWOTGRRESC.WaveObservableTransportGeometryRegimeResilienceConsumerFromMinimal cl →
  WaveObservableTransportGeometryRegimeIntegrityConsumerFromMinimal cl
canonicalWaveObservableTransportGeometryRegimeIntegrityConsumer waveObsTransportGeometryRegimeResilience =
  waveObservableTransportGeometryRegimeIntegrityConsumer
    waveObsTransportGeometryRegimeResilience
    KLRWOTGRINT.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
