module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeTheorem as KLRWOTGR
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
  field
    recoveredWaveObservableTransportGeometryRegime :
      KLRWOTGR.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
    KLRWOTGR.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
