module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem as KLRWOTGREQ
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeEquilibrium :
      KLRWOTGREQ.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeConvergenceTheorem
    KLRWOTGREQ.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
