module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem as KLRWOTGRCONS
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeConsistency :
      KLRWOTGRCONS.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
    KLRWOTGRCONS.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConsistencyTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
