module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem as KLRWOTGREQ
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeEquilibrium :
      KLRWOTGREQ.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeAlignmentTheorem
    KLRWOTGREQ.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
