module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem as KLRWOTGRINV
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeInvariance :
      KLRWOTGRINV.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeRobustnessTheorem
    KLRWOTGRINV.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeInvarianceTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
