module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeResilienceTheorem as KLRWOTGRRES
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeResilience :
      KLRWOTGRRES.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeResilienceTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
    KLRWOTGRRES.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeResilienceTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
