module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem as KLRWOTGREQ
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeEquilibrium :
      KLRWOTGREQ.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeFidelityTheorem
    KLRWOTGREQ.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
