module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem as KLRWOTGRS
open import DASHI.Physics.Closure.KnownLimitsCompleteLocalRegimeTheorem as KLCLR

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeStability :
      KLRWOTGRS.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
    completeLocalRegime :
      KLCLR.KnownLimitsCompleteLocalRegimeTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeCompletenessTheorem
    KLRWOTGRS.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
    KLCLR.canonicalKnownLimitsCompleteLocalRegimeTheorem
