module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem as KLRWOTGRHAR
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeHarmony :
      KLRWOTGRHAR.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeBalanceTheorem
    KLRWOTGRHAR.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
