module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem as KLRWOTGRINT
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeIntegrity :
      KLRWOTGRINT.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeHarmonyTheorem
    KLRWOTGRINT.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeIntegrityTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
