module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem as KLRWOTGRC
open import DASHI.Physics.Closure.KnownLimitsCompleteLocalRegimeTheorem as KLCLR

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeCoherence :
      KLRWOTGRC.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
    completeLocalRegime :
      KLCLR.KnownLimitsCompleteLocalRegimeTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeStabilityTheorem
    KLRWOTGRC.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCoherenceTheorem
    KLCLR.canonicalKnownLimitsCompleteLocalRegimeTheorem
