module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem as KLRWOTGRCOH
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeCohesion :
      KLRWOTGRCOH.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeEquilibriumTheorem
    KLRWOTGRCOH.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
