module DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem where

open import Agda.Primitive using (Setω)

open import DASHI.Physics.Closure.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConcordanceTheorem as KLRWOTGRCONC
open import DASHI.Physics.Closure.KnownLimitsLocalPhysicsCoherenceTheorem as KLLPC

record KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem : Setω where
  constructor knownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
  field
    recoveredWaveObservableTransportGeometryRegimeConcordance :
      KLRWOTGRCONC.KnownLimitsRecoveredWaveObservableTransportGeometryRegimeConcordanceTheorem
    localPhysicsCoherence :
      KLLPC.KnownLimitsLocalPhysicsCoherenceTheorem

canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem :
  KnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem =
  knownLimitsRecoveredWaveObservableTransportGeometryRegimeCohesionTheorem
    KLRWOTGRCONC.canonicalKnownLimitsRecoveredWaveObservableTransportGeometryRegimeConcordanceTheorem
    KLLPC.canonicalKnownLimitsLocalPhysicsCoherenceTheorem
