module Ontology.Hecke.CurrentSaturatedContractiveCountPartitionPreservation where

open import Agda.Builtin.Equality using (_≡_; refl)

open import Ontology.Hecke.ContractiveCountLayer2Invariant
  using (contractiveCountFamily)
open import Ontology.Hecke.CurrentSaturatedForcedStableCollapse
  using
    ( CurrentSaturatedGenerator
    ; saturatedAnchoredTrajectory
    ; saturatedBalancedComposed
    ; saturatedBalancedCycle
    ; saturatedDenseComposed
    ; saturatedExplicitWidth2
    ; saturatedExplicitWidth3
    ; saturatedFullSupportCascade
    ; saturatedGeneratorClass
    ; saturatedSupportCascade
    )
open import Ontology.Hecke.DefectOrbitCollapseBridge
  using (primeImage)
open import Ontology.Hecke.FactorVecDefectOrbitSummaries
  using (profileSummaryFamily)

currentSaturatedContractiveCountFamilyAt : CurrentSaturatedGenerator → _
currentSaturatedContractiveCountFamilyAt c =
  contractiveCountFamily (primeImage (saturatedGeneratorClass c))

currentSaturatedProfileSummaryFamilyAt : CurrentSaturatedGenerator → _
currentSaturatedProfileSummaryFamilyAt c =
  profileSummaryFamily (primeImage (saturatedGeneratorClass c))

CurrentSaturatedContractiveCountPreservesFullFamily : Set
CurrentSaturatedContractiveCountPreservesFullFamily =
  ∀ c₁ c₂ →
    currentSaturatedContractiveCountFamilyAt c₁
      ≡
    currentSaturatedContractiveCountFamilyAt c₂
      →
    currentSaturatedProfileSummaryFamilyAt c₁
      ≡
    currentSaturatedProfileSummaryFamilyAt c₂

currentSaturatedContractiveCountPreservesFullFamily :
  CurrentSaturatedContractiveCountPreservesFullFamily
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedExplicitWidth3 eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedDenseComposed eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedSupportCascade eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth3 saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedExplicitWidth3 eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedDenseComposed eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedSupportCascade eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedDenseComposed saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedExplicitWidth3 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedDenseComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedBalancedCycle eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedBalancedComposed eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedCycle saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedExplicitWidth3 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedDenseComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedBalancedCycle eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedBalancedComposed eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedBalancedComposed saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedExplicitWidth3 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedDenseComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedExplicitWidth2 eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedAnchoredTrajectory eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedExplicitWidth2 saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedExplicitWidth3 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedDenseComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedExplicitWidth2 eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedAnchoredTrajectory eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedAnchoredTrajectory saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedExplicitWidth3 eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedDenseComposed eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedSupportCascade eq = refl
currentSaturatedContractiveCountPreservesFullFamily saturatedSupportCascade saturatedFullSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedExplicitWidth3 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedDenseComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedBalancedCycle ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedBalancedComposed ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedExplicitWidth2 ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedAnchoredTrajectory ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedSupportCascade ()
currentSaturatedContractiveCountPreservesFullFamily saturatedFullSupportCascade saturatedFullSupportCascade eq = refl

record CurrentSaturatedContractiveCountPartitionSurface : Set₁ where
  field
    preservesFullFamily : CurrentSaturatedContractiveCountPreservesFullFamily

currentSaturatedContractiveCountPartitionSurface :
  CurrentSaturatedContractiveCountPartitionSurface
currentSaturatedContractiveCountPartitionSurface = record
  { preservesFullFamily = currentSaturatedContractiveCountPreservesFullFamily
  }
