module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.DurabilitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.OperabilitySummary as MTWOTGROPERS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.Summary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary
  field
    waveObservableTransportGeometryRegimeOperabilitySummary :
      MTWOTGROPERS.MoonshineTwinedWaveObservableTransportGeometryRegimeOperabilitySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeDurabilitySummary
    MTWOTGROPERS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeOperabilitySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
