module DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.TraceabilitySummary where

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.IntegritySummary as MTWOTGRINTS
open import DASHI.Physics.Moonshine.MoonshineTwinedWaveObservableTransportGeometry.Regime.Summary as MTWOTGRS

record MoonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary : Set where
  constructor moonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary
  field
    waveObservableTransportGeometryRegimeIntegritySummary :
      MTWOTGRINTS.MoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
    waveObservableTransportGeometryRegimeSummary :
      MTWOTGRS.MoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    summaryCount : Nat

canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary :
  MoonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary
canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary =
  moonshineTwinedWaveObservableTransportGeometryRegimeTraceabilitySummary
    MTWOTGRINTS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeIntegritySummary
    MTWOTGRS.canonicalMoonshineTwinedWaveObservableTransportGeometryRegimeSummary
    2
