module DASHI.Physics.Closure.Algebra.WaveRegime where

-- Short-path compatibility layer for the current wave-regime algebra ladder.

open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeCoherenceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeStabilityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeCompletenessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeSoundnessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeConsistencyTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeInvarianceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeRobustnessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeResilienceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeHarmonyTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeBalanceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeSymmetryTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeContinuityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeCompatibilityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeConcordanceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeCohesionTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeEquilibriumTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeConvergenceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometryRegimeAlignmentTheorem public

