module DASHI.Physics.Closure.Algebra.WaveRegime where

-- Short-path compatibility layer for the current wave-regime algebra ladder.

open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.Theorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.CoherenceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.StabilityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.CompletenessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.SoundnessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ConsistencyTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.InvarianceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.RobustnessTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ResilienceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.HarmonyTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.BalanceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.SymmetryTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ContinuityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.CompatibilityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ConcordanceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.CohesionTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.EquilibriumTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ConvergenceTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.AlignmentTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.PrecisionTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ResolutionTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.CalibrationTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.NormalizationTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.RefinementTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.IntegrationTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.SynthesisTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.FusionTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.FidelityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.LegibilityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.TransparencyTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.ClarityTheorem public
open import DASHI.Physics.Closure.ParametricAlgebraicWaveObservableTransportGeometry.Regime.IntegrityTheorem public
